.baremetal-test:
  extends:
    - .test
  # Cancel job if a newer commit is pushed to the same branch
  interruptible: true
  before_script:
    - !reference [.download_s3, before_script]
  variables:
    BM_ROOTFS: /rootfs-${DEBIAN_ARCH}
  artifacts:
    when: always
    name: "${CI_PROJECT_NAME}_${CI_JOB_NAME_SLUG}"
    paths:
      - results/
      - serial*.txt
    exclude:
      - results/*.shader_cache
    reports:
      junit: results/junit.xml

# ARM testing of bare-metal boards attached to an x86 gitlab-runner system
.baremetal-test-arm32-gl:
  extends:
    - .baremetal-test
    - .use-debian/baremetal_arm32_test-gl
  variables:
    DEBIAN_ARCH: armhf
    S3_ARTIFACT_NAME: mesa-arm32-default-debugoptimized
  needs:
    - job: debian/baremetal_arm32_test-gl
      optional: true
    - job: debian-arm32
      artifacts: false
    - !reference [.required-for-hardware-jobs, needs]

# ARM64 testing of bare-metal boards attached to an x86 gitlab-runner system
.baremetal-test-arm64-gl:
  extends:
    - .baremetal-test
    - .use-debian/baremetal_arm64_test-gl
  variables:
    DEBIAN_ARCH: arm64
    S3_ARTIFACT_NAME: mesa-arm64-default-debugoptimized
  needs:
    - job: debian/baremetal_arm64_test-gl
      optional: true
    - job: debian-arm64
      artifacts: false
    - !reference [.required-for-hardware-jobs, needs]

# ARM64 testing of bare-metal boards attached to an x86 gitlab-runner system
.baremetal-test-arm64-vk:
  extends:
    - .baremetal-test
    - .use-debian/baremetal_arm64_test-vk
  variables:
    DEBIAN_ARCH: arm64
    S3_ARTIFACT_NAME: mesa-arm64-default-debugoptimized
  needs:
    - job: debian/baremetal_arm64_test-vk
      optional: true
    - job: debian-arm64
      artifacts: false
    - !reference [.required-for-hardware-jobs, needs]

# ARM32/64 testing of bare-metal boards attached to an x86 gitlab-runner system, using an asan mesa build
.baremetal-arm32-asan-test-gl:
  variables:
    S3_ARTIFACT_NAME: mesa-arm32-asan-debugoptimized
    DEQP_FORCE_ASAN: 1
  needs:
    - job: debian/baremetal_arm32_test-gl
      optional: true
    - job: debian-arm32-asan
      artifacts: false
    - !reference [.required-for-hardware-jobs, needs]

.baremetal-arm64-asan-test-gl:
  variables:
    S3_ARTIFACT_NAME: mesa-arm64-asan-debugoptimized
    DEQP_FORCE_ASAN: 1
  needs:
    - job: debian/baremetal_arm64_test-gl
      optional: true
    - job: debian-arm64-asan
      artifacts: false
    - !reference [.required-for-hardware-jobs, needs]

.baremetal-arm64-asan-test-vk:
  variables:
    S3_ARTIFACT_NAME: mesa-arm64-asan-debugoptimized
    DEQP_FORCE_ASAN: 1
  needs:
    - job: debian/baremetal_arm64_test-vk
      optional: true
    - job: debian-arm64-asan
      artifacts: false
    - !reference [.required-for-hardware-jobs, needs]

.baremetal-arm64-ubsan-test-gl:
  extends:
    - .baremetal-test
    - .use-debian/baremetal_arm64_test-gl
  variables:
    S3_ARTIFACT_NAME: mesa-arm64-ubsan-debugoptimized
  needs:
    - job: debian/baremetal_arm64_test-gl
      optional: true
    - job: debian-arm64-ubsan
      artifacts: false
    - !reference [.required-for-hardware-jobs, needs]

.baremetal-arm64-ubsan-test-vk:
  extends:
    - .baremetal-test
    - .use-debian/baremetal_arm64_test-vk
  variables:
    S3_ARTIFACT_NAME: mesa-arm64-ubsan-debugoptimized
  needs:
    - job: debian/baremetal_arm64_test-vk
      optional: true
    - job: debian-arm64-ubsan
      artifacts: false
    - !reference [.required-for-hardware-jobs, needs]

.baremetal-deqp-test:
  variables:
    HWCI_TEST_SCRIPT: "/install/deqp-runner.sh"
    FDO_CI_CONCURRENT: 0  # Default to number of CPUs
