# Build the CI Alpine docker images.
#
# MESA_IMAGE_TAG is the tag of the docker image used by later stage jobs. If the
# image doesn't exist yet, the container stage job generates it.
#
# In order to generate a new image, one should generally change the tag.
# While removing the image from the registry would also work, that's not
# recommended except for ephemeral images during development: Replacing
# an image after a significant amount of time might pull in newer
# versions of gcc/clang or other packages, which might break the build
# with older commits using the same tag.
#
# After merging a change resulting in generating a new image to the
# main repository, it's recommended to remove the image from the source
# repository's container registry, so that the image from the main
# repository's registry will be used there as well.

# Alpine based x86_64 build image
.alpine/x86_64_build-base:
  extends:
    - .fdo.container-build@alpine
    - .container
  variables:
    FDO_DISTRIBUTION_VERSION: "3.21"
    FDO_BASE_IMAGE: alpine:$FDO_DISTRIBUTION_VERSION  # since cbuild ignores it

# Alpine based x86_64 build image
alpine/x86_64_build:
  extends:
    - .alpine/x86_64_build-base
  variables:
    MESA_IMAGE_TAG: &alpine-x86_64_build ${ALPINE_X86_64_BUILD_TAG}
    LLVM_VERSION: &alpine-llvm_version 19
  rules:
    - !reference [.container, rules]
    # Note: the next three lines must remain in that order, so that the rules
    # in `linkcheck-docs` catch nightly pipelines before the rules in `deploy-docs`
    # exclude them.
    - !reference [linkcheck-docs, rules]
    - !reference [deploy-docs, rules]
    - !reference [test-docs, rules]

.use-alpine/x86_64_build:
  tags:
    - $FDO_RUNNER_JOB_PRIORITY_TAG_X86_64
  extends:
    - .set-image
  variables:
    MESA_IMAGE_PATH: "alpine/x86_64_build"
    MESA_IMAGE_TAG: *alpine-x86_64_build
    LLVM_VERSION: *alpine-llvm_version
  needs:
    - job: sanity
      optional: true
    - job: alpine/x86_64_build
      optional: true

# Alpine based x86_64 image for LAVA SSH dockerized client
alpine/x86_64_lava_ssh_client:
  extends:
    - .alpine/x86_64_build-base
  variables:
    MESA_IMAGE_TAG: &alpine-x86_64_lava_ssh_client ${ALPINE_X86_64_LAVA_SSH_TAG}

# Alpine based x86_64 image to run LAVA jobs
alpine/x86_64_lava-trigger:
  extends:
    - .alpine/x86_64_build-base
  variables:
    MESA_IMAGE_TAG: &alpine-x86_64_lava_trigger ${ALPINE_X86_64_LAVA_TRIGGER_TAG}
