name: macOS-CI

# Permite que o workflow seja executado manualmente e também no push
on:
  push:
  workflow_dispatch:  # Isso adiciona o botão "Run workflow" no GitHub Actions

permissions:
  contents: read

jobs:
  macOS-CI:
    strategy:
      matrix:
        glx_option: ['dri', 'xlib']
    runs-on: macos-11
    env:
      GALLIUM_DUMP_CPU: true
      MESON_EXEC: /Users/runner/Library/Python/3.11/bin/meson

    steps:
      # 1️⃣ Checkout do código
      - name: Checkout
        uses: actions/checkout@v3

      # 2️⃣ Instalar dependências via Homebrew
      - name: Install Dependencies
        run: |
          cat > Brewfile <<EOL
          brew "bison"
          brew "expat"
          brew "gettext"
          brew "libx11"
          brew "libxcb"
          brew "libxdamage"
          brew "libxext"
          brew "molten-vk"
          brew "ninja"
          brew "pkg-config"
          brew "python@3.10"
          EOL

          brew update
          brew bundle --verbose

      # 3️⃣ Instalar Mako e Meson via pip
      - name: Install Mako and meson
        run: pip3 install --user mako meson

      # 4️⃣ Configuração do build
      - name: Configure
        run: |
          cat > native_config <<EOL
          [binaries]
          llvm-config = '/usr/local/opt/llvm/bin/llvm-config'
          EOL
          $MESON_EXEC . build --native-file=native_config \
            -Dmoltenvk-dir=$(brew --prefix molten-vk) \
            -Dbuild-tests=true \
            -Dgallium-drivers=swrast,zink \
            -Dglx=${{ matrix.glx_option }}

      # 5️⃣ Compilação
      - name: Build
        run: $MESON_EXEC compile -C build

      # 6️⃣ Testes
      - name: Test
        run: $MESON_EXEC test -C build --print-errorlogs

      # 7️⃣ Instalação local
      - name: Install
        run: $MESON_EXEC install -C build --destdir $PWD/install

      # 8️⃣ Upload de artefatos usando a v4
      - name: Upload Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: macos-${{ matrix.glx_option }}-result
          path: |
            build/meson-logs/
            install/
          retention-days: 5
